### ISSUE TITLE
Create basic working structure.

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/watchmen#2]
- [ ] Add database for urls (mangodb? We just need to store a list of strings, everything else can be cashed in runtime).
- [x] Add newspaper.
- [x] Implement basic curator (checking if url is valid).
- [x] Cache articles.

**Comment by mircealungu** [comment]
@Lukeslux regarding the caching business: we should make sure that we reuse as much as we can from the newspaper lib: http://newspaper.readthedocs.io/en/latest/user_guide/quickstart.html#article-caching
